// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERROR       Status = 2
	Status_STATUS_DONE        Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_DONE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_DONE":        3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bridge_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_bridge_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

type JobKind int32

const (
	JobKind_JOB_KIND_UNSPECIFIED   JobKind = 0
	JobKind_JOB_KIND_QUERY         JobKind = 1
	JobKind_JOB_KIND_PING_SERVICE  JobKind = 2
	JobKind_JOB_KIND_PING_DATABASE JobKind = 3
	JobKind_JOB_KIND_CONNECT       JobKind = 4
	JobKind_JOB_KIND_DISCONNECT    JobKind = 5
)

// Enum value maps for JobKind.
var (
	JobKind_name = map[int32]string{
		0: "JOB_KIND_UNSPECIFIED",
		1: "JOB_KIND_QUERY",
		2: "JOB_KIND_PING_SERVICE",
		3: "JOB_KIND_PING_DATABASE",
		4: "JOB_KIND_CONNECT",
		5: "JOB_KIND_DISCONNECT",
	}
	JobKind_value = map[string]int32{
		"JOB_KIND_UNSPECIFIED":   0,
		"JOB_KIND_QUERY":         1,
		"JOB_KIND_PING_SERVICE":  2,
		"JOB_KIND_PING_DATABASE": 3,
		"JOB_KIND_CONNECT":       4,
		"JOB_KIND_DISCONNECT":    5,
	}
)

func (x JobKind) Enum() *JobKind {
	p := new(JobKind)
	*p = x
	return p
}

func (x JobKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bridge_proto_enumTypes[1].Descriptor()
}

func (JobKind) Type() protoreflect.EnumType {
	return &file_proto_bridge_proto_enumTypes[1]
}

func (x JobKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobKind.Descriptor instead.
func (JobKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AgentHello) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AgentHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHello) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AgentHello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          JobKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=bridge.JobKind" json:"kind,omitempty"`
	Sql           string                 `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	IncludeSrc    bool                   `protobuf:"varint,4,opt,name=include_src,json=includeSrc,proto3" json:"include_src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetKind() JobKind {
	if x != nil {
		return x.Kind
	}
	return JobKind_JOB_KIND_UNSPECIFIED
}

func (x *JobRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *JobRequest) GetIncludeSrc() bool {
	if x != nil {
		return x.IncludeSrc
	}
	return false
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=bridge.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *JobResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentToServer_Hello
	//	*AgentToServer_JobResult
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_Log
	Payload       isAgentToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_proto_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *AgentToServer) GetPayload() isAgentToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentToServer) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToServer) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetLog() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isAgentToServer_Payload interface {
	isAgentToServer_Payload()
}

type AgentToServer_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentToServer_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,2,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_Log struct {
	Log *LogEntry `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

func (*AgentToServer_Hello) isAgentToServer_Payload() {}

func (*AgentToServer_JobResult) isAgentToServer_Payload() {}

func (*AgentToServer_Heartbeat) isAgentToServer_Payload() {}

func (*AgentToServer_Log) isAgentToServer_Payload() {}

type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToAgent_JobRequest
	Payload       isServerToAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_proto_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *ServerToAgent) GetPayload() isServerToAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToAgent) GetJobRequest() *JobRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_JobRequest); ok {
			return x.JobRequest
		}
	}
	return nil
}

type isServerToAgent_Payload interface {
	isServerToAgent_Payload()
}

type ServerToAgent_JobRequest struct {
	JobRequest *JobRequest `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3,oneof"`
}

func (*ServerToAgent_JobRequest) isServerToAgent_Payload() {}

var File_proto_bridge_proto protoreflect.FileDescriptor

const file_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\x12proto/bridge.proto\x12\x06bridge\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x126\n" +
	"\x06labels\x18\x05 \x03(\v2\x1e.bridge.AgentHello.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\tHeartbeat\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xd7\x01\n" +
	"\bLogEntry\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x06fields\x18\x04 \x03(\v2\x1c.bridge.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x03Row\x12/\n" +
	"\x06fields\x18\x01 \x03(\v2\x17.bridge.Row.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"{\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x0f.bridge.JobKindR\x04kind\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x12\x1f\n" +
	"\vinclude_src\x18\x04 \x01(\bR\n" +
	"includeSrc\"\x85\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.bridge.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\x04rows\x18\x04 \x03(\v2\v.bridge.RowR\x04rows\"\xd3\x01\n" +
	"\rAgentToServer\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.bridge.AgentHelloH\x00R\x05hello\x122\n" +
	"\n" +
	"job_result\x18\x02 \x01(\v2\x11.bridge.JobResultH\x00R\tjobResult\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.bridge.HeartbeatH\x00R\theartbeat\x12$\n" +
	"\x03log\x18\x04 \x01(\v2\x10.bridge.LogEntryH\x00R\x03logB\t\n" +
	"\apayload\"Q\n" +
	"\rServerToAgent\x125\n" +
	"\vjob_request\x18\x01 \x01(\v2\x12.bridge.JobRequestH\x00R\n" +
	"jobRequestB\t\n" +
	"\apayload*R\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x03*\x9d\x01\n" +
	"\aJobKind\x12\x18\n" +
	"\x14JOB_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_KIND_QUERY\x10\x01\x12\x19\n" +
	"\x15JOB_KIND_PING_SERVICE\x10\x02\x12\x1a\n" +
	"\x16JOB_KIND_PING_DATABASE\x10\x03\x12\x14\n" +
	"\x10JOB_KIND_CONNECT\x10\x04\x12\x17\n" +
	"\x13JOB_KIND_DISCONNECT\x10\x052K\n" +
	"\fAgentService\x12;\n" +
	"\aConnect\x12\x15.bridge.AgentToServer\x1a\x15.bridge.ServerToAgent(\x010\x01B>Z<github.com/BeardedWonderDev/DIS-Reader/internal/bridge/protob\x06proto3"

var (
	file_proto_bridge_proto_rawDescOnce sync.Once
	file_proto_bridge_proto_rawDescData []byte
)

func file_proto_bridge_proto_rawDescGZIP() []byte {
	file_proto_bridge_proto_rawDescOnce.Do(func() {
		file_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)))
	})
	return file_proto_bridge_proto_rawDescData
}

var file_proto_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_bridge_proto_goTypes = []any{
	(Status)(0),                   // 0: bridge.Status
	(JobKind)(0),                  // 1: bridge.JobKind
	(*AgentHello)(nil),            // 2: bridge.AgentHello
	(*Heartbeat)(nil),             // 3: bridge.Heartbeat
	(*LogEntry)(nil),              // 4: bridge.LogEntry
	(*Row)(nil),                   // 5: bridge.Row
	(*JobRequest)(nil),            // 6: bridge.JobRequest
	(*JobResult)(nil),             // 7: bridge.JobResult
	(*AgentToServer)(nil),         // 8: bridge.AgentToServer
	(*ServerToAgent)(nil),         // 9: bridge.ServerToAgent
	nil,                           // 10: bridge.AgentHello.LabelsEntry
	nil,                           // 11: bridge.LogEntry.FieldsEntry
	nil,                           // 12: bridge.Row.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 14: google.protobuf.Value
}
var file_proto_bridge_proto_depIdxs = []int32{
	10, // 0: bridge.AgentHello.labels:type_name -> bridge.AgentHello.LabelsEntry
	13, // 1: bridge.Heartbeat.at:type_name -> google.protobuf.Timestamp
	13, // 2: bridge.LogEntry.at:type_name -> google.protobuf.Timestamp
	11, // 3: bridge.LogEntry.fields:type_name -> bridge.LogEntry.FieldsEntry
	12, // 4: bridge.Row.fields:type_name -> bridge.Row.FieldsEntry
	1,  // 5: bridge.JobRequest.kind:type_name -> bridge.JobKind
	0,  // 6: bridge.JobResult.status:type_name -> bridge.Status
	5,  // 7: bridge.JobResult.rows:type_name -> bridge.Row
	2,  // 8: bridge.AgentToServer.hello:type_name -> bridge.AgentHello
	7,  // 9: bridge.AgentToServer.job_result:type_name -> bridge.JobResult
	3,  // 10: bridge.AgentToServer.heartbeat:type_name -> bridge.Heartbeat
	4,  // 11: bridge.AgentToServer.log:type_name -> bridge.LogEntry
	6,  // 12: bridge.ServerToAgent.job_request:type_name -> bridge.JobRequest
	14, // 13: bridge.Row.FieldsEntry.value:type_name -> google.protobuf.Value
	8,  // 14: bridge.AgentService.Connect:input_type -> bridge.AgentToServer
	9,  // 15: bridge.AgentService.Connect:output_type -> bridge.ServerToAgent
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_bridge_proto_init() }
func file_proto_bridge_proto_init() {
	if File_proto_bridge_proto != nil {
		return
	}
	file_proto_bridge_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentToServer_Hello)(nil),
		(*AgentToServer_JobResult)(nil),
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_Log)(nil),
	}
	file_proto_bridge_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerToAgent_JobRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bridge_proto_goTypes,
		DependencyIndexes: file_proto_bridge_proto_depIdxs,
		EnumInfos:         file_proto_bridge_proto_enumTypes,
		MessageInfos:      file_proto_bridge_proto_msgTypes,
	}.Build()
	File_proto_bridge_proto = out.File
	file_proto_bridge_proto_goTypes = nil
	file_proto_bridge_proto_depIdxs = nil
}
